### ISSUE TITLE
svtplay.se's site redesign broke the app

### ISSUE THREAD

**Issue by rydenius** [Kantaris/PlaySE-Smart-TV-app#11]
It looks to me like the newly launched version of svtplay.se made the current version of the PlaySE Smart TV app unusable. (Maybe that was part of their intention too?)

**Comment by Kantaris** [comment]
Var bara servern som kraschat. Allt ska fungera igen nu. Tack för att du meddelade mig.

**Comment by rydenius** [comment]
Vad skönt! Tack!

29 jan 2014 kl. 22:39 Tips: ikväll är sista kvällen att beställa orienteringskläder för 2014 via tullingesk.se, lösenord för inloggning är "brantan". Jörgen Kantaris notifications@github.com:
